### ISSUE TITLE
[Bug] Endless loop when logging public or private key with null value

### ISSUE THREAD

**Issue by Woody4618** [garbles-labs/Solana.Unity-Core#12]
**Describe the bug**
When you call toString on a public or private key which _key or _keyBytes are null there is an endless loop from the properties calling each other. 

**To Reproduce**
            PublicKey pubKey = new PublicKey("");
            pubKey.Key = null;
            Debug.Log(pubKey);

**Expected behavior**
There is no endless loop but instead returned null. 

**Additional context**
Ill make a pr for a fix

**Comment by GabrielePicco** [comment]
Closing as fixed in #13
