### ISSUE TITLE
Can you please release a nuget package or unitypackage  with out Unity3D.SDK, for unity?

### ISSUE THREAD

**Issue by devzhuchuanbo** [garbles-labs/Solana.Unity-Core#7]
**Is your feature request related to a problem? Please describe.**
This nuget package contains the Unity3D SDK, and importing it will cause duplication of unity dlls. Even if it is deleted, it will be imported again when the project is opened next time.

**Comment by devzhuchuanbo** [comment]
I didn't notice this repository[Solana.Unity-SDK](https://github.com/garbles-labs/Solana.Unity-SDK) yesterday, please delete this issue.

**Comment by GabrielePicco** [comment]
@devzhuchuanbo we removed the dependency in the latest DLLs, thanks for noticing. The next release will contain the fix.
